import type { Exception } from '../schemas';

export const DEMO_EXCEPTIONS: Exception[] = [
  // ── Vendor B – BoxCraft (conditional footnote discount) ────────────────────
  {
    exception_id: 'EX-B-001',
    rfx_id: 'rfx-001',
    vendor_id: 'V-B',
    line_id: null,
    type: 'ambiguous_discount',
    severity: 'medium',
    status: 'open',
    title: 'Conditional 5% volume discount not applied — threshold unknown',
    description:
      'BoxCraft quotes a 5% discount applicable when total PO value exceeds ₹10,00,000 (per footnote §3). This discount has NOT been applied to normalized prices. Buyer must confirm whether total PO will exceed the threshold before applying.',
    source_evidence: 'EV-B-002',
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-B-002',
    rfx_id: 'rfx-001',
    vendor_id: 'V-B',
    line_id: null,
    type: 'missing_freight',
    severity: 'medium',
    status: 'open',
    title: 'Freight quoted separately — landed cost not calculable per unit',
    description:
      'BoxCraft charges ₹6,200 per consignment to Hyderabad. This is a flat charge per delivery, not per-unit. Landed cost per line item depends on total units per delivery — which is unknown.',
    source_evidence: 'EV-B-003',
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-B-003',
    rfx_id: 'rfx-001',
    vendor_id: 'V-B',
    line_id: null,
    type: 'low_confidence_extraction',
    severity: 'low',
    status: 'open',
    title: 'PDF extraction: table alignment verified but footnote parsed from image layer',
    description:
      'Footnote §3 was extracted from an embedded image within the PDF. Text is clear but buyer should confirm the discount condition matches the vendor\'s intent.',
    source_evidence: 'EV-B-002',
    resolution_note: null,
    requires_buyer_action: false,
  },

  // ── Vendor C – GlobalPack (USD, missing lines, partial questionnaire) ───────
  {
    exception_id: 'EX-C-001',
    rfx_id: 'rfx-001',
    vendor_id: 'V-C',
    line_id: null,
    type: 'currency_conversion_applied',
    severity: 'low',
    status: 'open',
    title: 'USD prices converted to INR at demo FX rate (₹84/USD)',
    description:
      'All GlobalPack prices are in USD. Normalized INR prices use a fixed demo FX rate of 1 USD = ₹84. In production, use a live or agreed FX rate. Currency risk is buyer\'s responsibility.',
    source_evidence: 'EV-C-001',
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-C-002',
    rfx_id: 'rfx-001',
    vendor_id: 'V-C',
    line_id: 'L22',
    type: 'missing_line',
    severity: 'high',
    status: 'open',
    title: 'L22 – Packing Chip Loose Fill: not quoted (out of scope)',
    description:
      'GlobalPack explicitly stated L22 (Packing Chip) is outside their product scope and cannot be quoted. This line is excluded from GlobalPack\'s total.',
    source_evidence: 'EV-C-003',
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-C-003',
    rfx_id: 'rfx-001',
    vendor_id: 'V-C',
    line_id: 'L27',
    type: 'missing_line',
    severity: 'high',
    status: 'open',
    title: 'L27 – Anti-Static Box: not quoted (out of scope)',
    description:
      'GlobalPack explicitly stated L27 (Anti-Static Box) is outside their product scope.',
    source_evidence: 'EV-C-003',
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-C-004',
    rfx_id: 'rfx-001',
    vendor_id: 'V-C',
    line_id: null,
    type: 'missing_questionnaire_answer',
    severity: 'medium',
    status: 'open',
    title: 'Q4 and Q7 not answered in questionnaire',
    description:
      'GlobalPack did not answer Q4 (emergency order capability) or Q7 (rejection/replacement policy). These are required fields.',
    source_evidence: null,
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-C-005',
    rfx_id: 'rfx-001',
    vendor_id: 'V-C',
    line_id: null,
    type: 'missing_freight',
    severity: 'medium',
    status: 'open',
    title: 'Freight stated in prose — interpreted as ₹8,500 flat per delivery',
    description:
      'Freight was described in prose within a separate DOCX file: "A flat delivery surcharge of ₹8,500 applies per delivery to Hyderabad." This has been applied as a flat per-delivery freight charge, not per-unit. Buyer should confirm.',
    source_evidence: 'EV-C-002',
    resolution_note: null,
    requires_buyer_action: true,
  },

  // ── Vendor D – SwiftPack (OCR, unit ambiguity) ────────────────────────────
  {
    exception_id: 'EX-D-001',
    rfx_id: 'rfx-001',
    vendor_id: 'V-D',
    line_id: 'L01',
    type: 'unit_mismatch',
    severity: 'critical',
    status: 'open',
    title: 'L01 – Unit "box" is ambiguous — cannot normalize to pieces',
    description:
      'SwiftPack quoted ₹820/box for L01 (5-ply box 400×300×250). The unit "box" is ambiguous — it could refer to 1 individual piece, or a bundle/pack. Cannot convert to per-piece price without clarification from vendor.',
    source_evidence: 'EV-D-001',
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-D-002',
    rfx_id: 'rfx-001',
    vendor_id: 'V-D',
    line_id: 'L02',
    type: 'unit_mismatch',
    severity: 'critical',
    status: 'open',
    title: 'L02 – Unit "box" ambiguous — cannot normalize',
    description:
      'Same issue as L01. ₹1,200/box quoted but pieces-per-box unknown.',
    source_evidence: 'EV-D-002',
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-D-003',
    rfx_id: 'rfx-001',
    vendor_id: 'V-D',
    line_id: 'L03',
    type: 'unit_mismatch',
    severity: 'critical',
    status: 'open',
    title: 'L03 – Unit "box" ambiguous — cannot normalize',
    description:
      '₹580/box quoted but pieces-per-box unknown. Cannot normalize without clarification.',
    source_evidence: 'EV-D-001',
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-D-004',
    rfx_id: 'rfx-001',
    vendor_id: 'V-D',
    line_id: null,
    type: 'low_confidence_extraction',
    severity: 'medium',
    status: 'open',
    title: 'Image/OCR extraction — medium confidence on all values',
    description:
      'Vendor D submitted a photographed rate card (JPEG). OCR was applied. Most values extracted with 88–94% confidence. All values require buyer review before use in calculations.',
    source_evidence: 'EV-D-003',
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-D-005',
    rfx_id: 'rfx-001',
    vendor_id: 'V-D',
    line_id: 'L29',
    type: 'missing_line',
    severity: 'high',
    status: 'open',
    title: 'L29 – Oversized Box 800×600×600: not found in OCR extraction',
    description:
      'Line L29 was not found in the photographed rate card. It may have been cropped or missed during image capture. Vendor should be asked to confirm.',
    source_evidence: 'EV-D-003',
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-D-006',
    rfx_id: 'rfx-001',
    vendor_id: 'V-D',
    line_id: null,
    type: 'missing_freight',
    severity: 'high',
    status: 'open',
    title: 'Freight not specified anywhere in rate card',
    description:
      'No freight terms found in the photographed rate card. Freight state is "unknown" for all SwiftPack lines. Landed cost cannot be calculated.',
    source_evidence: 'EV-D-003',
    resolution_note: null,
    requires_buyer_action: true,
  },

  // ── Vendor E – QuickBox Express (email, ambiguous references) ────────────
  {
    exception_id: 'EX-E-001',
    rfx_id: 'rfx-001',
    vendor_id: 'V-E',
    line_id: 'L02',
    type: 'ambiguous_reference',
    severity: 'high',
    status: 'open',
    title: 'L02 – "Rest same as last year" — no 2023 contract to resolve',
    description:
      'QuickBox\'s email states pricing for L02, L03, L04, L21, L26 is "same as last year" or "same pricing structure as 2023 contract." No 2023 contract data is available to resolve these references. These lines are flagged as needs_review.',
    source_evidence: 'EV-E-001',
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-E-002',
    rfx_id: 'rfx-001',
    vendor_id: 'V-E',
    line_id: 'L22',
    type: 'missing_line',
    severity: 'high',
    status: 'open',
    title: 'L22, L27, L28 – Not in QuickBox catalogue',
    description:
      'QuickBox explicitly stated L22 (Packing Chips), L27 (Anti-Static Box), and L28 (Tri-Wall Board) are not in their catalogue.',
    source_evidence: 'EV-E-003',
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-E-003',
    rfx_id: 'rfx-001',
    vendor_id: 'V-E',
    line_id: null,
    type: 'missing_questionnaire_answer',
    severity: 'critical',
    status: 'open',
    title: 'Questionnaire largely unanswered — 6 of 8 questions missing',
    description:
      'QuickBox submitted pricing via email only. Q1 (ISO), Q2 (volume), Q3 (lead time), Q4 (emergency), Q6 (batch traceability), Q7 (rejection policy) and Q8 (capacity) were not answered. Cannot qualify this vendor.',
    source_evidence: null,
    resolution_note: null,
    requires_buyer_action: true,
  },
  {
    exception_id: 'EX-E-004',
    rfx_id: 'rfx-001',
    vendor_id: 'V-E',
    line_id: null,
    type: 'missing_freight',
    severity: 'medium',
    status: 'open',
    title: 'Freight "extra as applicable" — amount unknown',
    description:
      'QuickBox stated "Freight will be extra" and "freight charges as applicable" but provided no rate or estimate. Landed cost cannot be calculated for any QuickBox line.',
    source_evidence: 'EV-E-003',
    resolution_note: null,
    requires_buyer_action: true,
  },

  // ── Vendor A – PackPro ──────────────────────────────────────────────────────
  {
    exception_id: 'EX-A-001',
    rfx_id: 'rfx-001',
    vendor_id: 'V-A',
    line_id: null,
    type: 'missing_freight',
    severity: 'low',
    status: 'open',
    title: 'Freight excluded — to be quoted separately at actuals',
    description:
      'PackPro states freight is excluded and will be charged at actual cost. Minimum freight ₹4,500. Landed cost cannot be calculated per-unit.',
    source_evidence: 'EV-A-002',
    resolution_note: null,
    requires_buyer_action: false,
  },
];
