import type { RFx } from '../schemas';

export const DEMO_RFX: RFx = {
  rfx_id: 'rfx-001',
  name: 'Corrugated Packaging Annual Sourcing',
  category: 'Corrugated Packaging',
  delivery_location: 'Hyderabad',
  currency: 'INR',
  status: 'responses_received',
  created_at: '2024-01-15',
  deadline: '2024-02-15',
  commercial_requirements:
    'All prices must be inclusive of taxes unless stated otherwise. Payment terms: Net 30 days. Minimum order quantities apply. Freight to be quoted separately unless included in unit price. Quotes valid for minimum 90 days.',
  questionnaire: [
    {
      question_id: 'q1',
      text: 'Are you ISO 9001:2015 certified?',
      type: 'yes_no',
      required: true,
      qualification_rule: 'Must be Yes for qualification',
    },
    {
      question_id: 'q2',
      text: 'What is your required minimum monthly volume capacity (units)?',
      type: 'numeric',
      required: true,
    },
    {
      question_id: 'q3',
      text: 'What is your standard lead time in days?',
      type: 'numeric',
      required: true,
      qualification_rule: 'Must be ≤ 7 days for qualification',
    },
    {
      question_id: 'q4',
      text: 'Can you fulfill emergency orders within 48 hours?',
      type: 'yes_no',
      required: false,
    },
    {
      question_id: 'q5',
      text: 'Describe your quality inspection process.',
      type: 'text',
      required: true,
    },
    {
      question_id: 'q6',
      text: 'Do you provide batch traceability for all shipments?',
      type: 'yes_no',
      required: true,
      qualification_rule: 'Must be Yes for qualification',
    },
    {
      question_id: 'q7',
      text: 'What is your rejection and replacement policy?',
      type: 'text',
      required: true,
    },
    {
      question_id: 'q8',
      text: 'What is your monthly production capacity (units)?',
      type: 'numeric',
      required: true,
    },
  ],
  line_items: [
    {
      line_id: 'L01',
      item_name: 'Corrugated Box 400×300×250',
      description: 'Standard export-grade corrugated shipping box',
      specification: '5-ply, B-flute, 150 GSM kraft liner, RSC style',
      quantity: 50000,
      uom: 'pieces',
      required_delivery_date: '2024-03-01',
      category: 'Boxes',
    },
    {
      line_id: 'L02',
      item_name: 'Corrugated Box 600×400×400',
      description: 'Large heavy-duty corrugated shipping box',
      specification: '7-ply, BC-flute, 180 GSM kraft liner, RSC style',
      quantity: 20000,
      uom: 'pieces',
      required_delivery_date: '2024-03-01',
      category: 'Boxes',
    },
    {
      line_id: 'L03',
      item_name: 'Corrugated Box 300×200×200',
      description: 'Small standard corrugated box for light goods',
      specification: '3-ply, B-flute, 120 GSM kraft liner, RSC style',
      quantity: 80000,
      uom: 'pieces',
      required_delivery_date: '2024-03-15',
      category: 'Boxes',
    },
    {
      line_id: 'L04',
      item_name: 'Corrugated Box 500×350×300',
      description: 'Medium corrugated box, double-wall construction',
      specification: '5-ply, BC-flute, 160 GSM kraft liner',
      quantity: 35000,
      uom: 'pieces',
      required_delivery_date: '2024-03-01',
      category: 'Boxes',
    },
    {
      line_id: 'L05',
      item_name: 'Corrugated Sheet 1200×800',
      description: 'Flat corrugated sheet for custom packaging and void fill',
      specification: '3-ply, B-flute, 120 GSM, unprinted',
      quantity: 100000,
      uom: 'pieces',
      required_delivery_date: '2024-03-15',
      category: 'Sheets',
    },
    {
      line_id: 'L06',
      item_name: 'Corrugated Sheet 800×600',
      description: 'Medium flat corrugated sheet for layering',
      specification: '3-ply, E-flute, 100 GSM',
      quantity: 60000,
      uom: 'pieces',
      required_delivery_date: '2024-03-15',
      category: 'Sheets',
    },
    {
      line_id: 'L07',
      item_name: 'Die-Cut Box – Mailer 250×180×80',
      description: 'E-commerce mailer box with tuck-in lid',
      specification: '3-ply, E-flute, 130 GSM, printed 2-color',
      quantity: 40000,
      uom: 'pieces',
      required_delivery_date: '2024-03-01',
      category: 'Mailers',
    },
    {
      line_id: 'L08',
      item_name: 'Die-Cut Box – Mailer 350×250×120',
      description: 'Large e-commerce mailer box',
      specification: '3-ply, E-flute, 130 GSM, printed 2-color',
      quantity: 25000,
      uom: 'pieces',
      required_delivery_date: '2024-03-01',
      category: 'Mailers',
    },
    {
      line_id: 'L09',
      item_name: 'Corrugated Roll – B-flute 1200mm',
      description: 'Corrugated roll for wrapping and protection',
      specification: 'B-flute, 1200mm width, 150m roll',
      quantity: 2000,
      uom: 'rolls',
      required_delivery_date: '2024-03-15',
      category: 'Rolls',
    },
    {
      line_id: 'L10',
      item_name: 'Edge Protector Corner 50×50×5',
      description: 'L-shaped edge protector for pallet stacking',
      specification: 'Solid board, 50×50×5mm cross-section, 1000mm length',
      quantity: 150000,
      uom: 'pieces',
      required_delivery_date: '2024-03-15',
      category: 'Protection',
    },
    {
      line_id: 'L11',
      item_name: 'Honeycomb Panel 1200×800×30',
      description: 'Lightweight honeycomb panel for packing base',
      specification: 'Kraft paper honeycomb core, 30mm thick, 30lb',
      quantity: 10000,
      uom: 'pieces',
      required_delivery_date: '2024-04-01',
      category: 'Panels',
    },
    {
      line_id: 'L12',
      item_name: 'Corrugated Box 450×350×280',
      description: 'Square corrugated box for industrial goods',
      specification: '5-ply, BC-flute, 150 GSM',
      quantity: 30000,
      uom: 'pieces',
      required_delivery_date: '2024-03-15',
      category: 'Boxes',
    },
    {
      line_id: 'L13',
      item_name: 'Partition Divider Set – 6-cell',
      description: 'Corrugated partition for bottle/jar packaging',
      specification: '3-ply, B-flute, 6-cell configuration, 400×300 base',
      quantity: 20000,
      uom: 'sets',
      required_delivery_date: '2024-03-15',
      category: 'Inserts',
    },
    {
      line_id: 'L14',
      item_name: 'Partition Divider Set – 12-cell',
      description: 'Corrugated partition for smaller bottles',
      specification: '3-ply, B-flute, 12-cell configuration, 400×300 base',
      quantity: 15000,
      uom: 'sets',
      required_delivery_date: '2024-03-15',
      category: 'Inserts',
    },
    {
      line_id: 'L15',
      item_name: 'Pallet Tray 1200×800×100',
      description: 'Heavy-duty corrugated pallet tray',
      specification: '7-ply, BC-flute, 200 GSM, triple-wall base',
      quantity: 5000,
      uom: 'pieces',
      required_delivery_date: '2024-04-01',
      category: 'Pallets',
    },
    {
      line_id: 'L16',
      item_name: 'Corrugated Box 700×500×500',
      description: 'XL corrugated box for bulk shipments',
      specification: '7-ply, BC-flute, 200 GSM',
      quantity: 10000,
      uom: 'pieces',
      required_delivery_date: '2024-03-15',
      category: 'Boxes',
    },
    {
      line_id: 'L17',
      item_name: 'Inner Flap Tray 400×300×50',
      description: 'Shallow tray insert for layer packaging',
      specification: '3-ply, B-flute, 120 GSM',
      quantity: 45000,
      uom: 'pieces',
      required_delivery_date: '2024-03-15',
      category: 'Trays',
    },
    {
      line_id: 'L18',
      item_name: 'Inner Flap Tray 600×400×60',
      description: 'Large shallow tray insert',
      specification: '3-ply, B-flute, 130 GSM',
      quantity: 25000,
      uom: 'pieces',
      required_delivery_date: '2024-03-15',
      category: 'Trays',
    },
    {
      line_id: 'L19',
      item_name: 'Moisture-Resistant Box 400×300×250',
      description: 'Wax-coated corrugated box for perishable goods',
      specification: '5-ply, B-flute, wax-dipped, 160 GSM',
      quantity: 20000,
      uom: 'pieces',
      required_delivery_date: '2024-04-01',
      category: 'Speciality',
    },
    {
      line_id: 'L20',
      item_name: 'Corrugated Sleeve 300×200',
      description: 'Open-top corrugated sleeve for product display',
      specification: '3-ply, E-flute, 120 GSM',
      quantity: 30000,
      uom: 'pieces',
      required_delivery_date: '2024-03-15',
      category: 'Sleeves',
    },
    {
      line_id: 'L21',
      item_name: 'Corrugated Box 250×200×150',
      description: 'Small economy corrugated box',
      specification: '3-ply, B-flute, 120 GSM',
      quantity: 100000,
      uom: 'pieces',
      required_delivery_date: '2024-03-01',
      category: 'Boxes',
    },
    {
      line_id: 'L22',
      item_name: 'Packing Chip Loose Fill – 15kg',
      description: 'Biodegradable starch packing chips',
      specification: 'Starch-based, biodegradable, 15kg bag',
      quantity: 500,
      uom: 'bags',
      required_delivery_date: '2024-03-15',
      category: 'Void Fill',
    },
    {
      line_id: 'L23',
      item_name: 'Corrugated Roll – E-flute 900mm',
      description: 'E-flute roll for wrapping fragile items',
      specification: 'E-flute, 900mm width, 100m roll',
      quantity: 1500,
      uom: 'rolls',
      required_delivery_date: '2024-03-15',
      category: 'Rolls',
    },
    {
      line_id: 'L24',
      item_name: 'Display Ready Case 400×300×200',
      description: 'Retail-ready corrugated display case',
      specification: '5-ply, B-flute, printed 4-color, perforated front panel',
      quantity: 15000,
      uom: 'pieces',
      required_delivery_date: '2024-04-01',
      category: 'Display',
    },
    {
      line_id: 'L25',
      item_name: 'Corner Edge Protector 75×75×5',
      description: 'Heavy-duty corner protector for furniture',
      specification: 'Solid board, 75×75×5mm, 1500mm length',
      quantity: 80000,
      uom: 'pieces',
      required_delivery_date: '2024-03-15',
      category: 'Protection',
    },
    {
      line_id: 'L26',
      item_name: 'Corrugated Box 350×250×200',
      description: 'Medium RSC corrugated box',
      specification: '5-ply, B-flute, 140 GSM',
      quantity: 60000,
      uom: 'pieces',
      required_delivery_date: '2024-03-01',
      category: 'Boxes',
    },
    {
      line_id: 'L27',
      item_name: 'Anti-Static Box 400×300×250',
      description: 'ESD-safe corrugated box for electronics',
      specification: '5-ply, carbon-coated, <10^6 ohm surface resistance',
      quantity: 8000,
      uom: 'pieces',
      required_delivery_date: '2024-04-01',
      category: 'Speciality',
    },
    {
      line_id: 'L28',
      item_name: 'Tri-Wall Board 1200×800',
      description: 'Heavy-duty triple-wall corrugated panel',
      specification: 'Triple-wall, 250 GSM, 18mm thick',
      quantity: 5000,
      uom: 'pieces',
      required_delivery_date: '2024-04-01',
      category: 'Panels',
    },
    {
      line_id: 'L29',
      item_name: 'Corrugated Box 800×600×600',
      description: 'Oversized corrugated box for machinery parts',
      specification: '7-ply, BC-flute, 200 GSM, double-wall',
      quantity: 5000,
      uom: 'pieces',
      required_delivery_date: '2024-04-01',
      category: 'Boxes',
    },
    {
      line_id: 'L30',
      item_name: 'Packing Tape Roll',
      description: 'Standard pressure-sensitive carton sealing tape',
      specification: '2" × 50m, 40 micron, acrylic adhesive',
      quantity: 5000,
      uom: 'rolls',
      required_delivery_date: '2024-03-01',
      category: 'Consumables',
    },
  ],
};
